services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: esg-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/chroma:/app/chroma
    env_file:
      - ./backend/.env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    networks:
      - esg_net
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esg-frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8000
    networks:
      - esg_net
    restart: unless-stopped

networks:
  esg_net:
    driver: bridge
