services:
  backend:
    build:
      context: ./backend
    container_name: esg-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/chroma:/app/chroma
    env_file:
      - ./backend/.env
    networks:
      - esg_net
    restart: unless-stopped
    command: >
      uvicorn server:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: ./frontend
    container_name: esg-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8000
    networks:
      - esg_net
    restart: unless-stopped

networks:
  esg_net:
    driver: bridge
